* Resolve all warnings and remove -Werror exceptions
* Simplify fix for Linux C++ test build (#595).

This patch resolves a TODO item in commit 818ead2 (Fix Linux C++ test build).
It appears that the undefined symbol errors of the following form:

> undefined reference to `boost::test_tools::tt_detail::print_log_value<decltype(nullptr)>::operator()(std::ostream&, decltype(nullptr))'

were due to the fact that GCC does not automatically emit such overloads unless
the relevant files are compiled with -std=c++11 or greater. (In this case, the
relevant files happen to be external Boost source files.) This patch adds the
-std=c++11 flag to the corresponding cmake build command, which allows us to
avoid defining the function overload ourselves.

See also:

https://svn.boost.org/trac10/ticket/12969

* Fix transposed memset arguments.

A call to memset() in vector_internals had its arguments apparently transposed,
with the length argument coming second instead of third. This patch swaps the
arguments to the correct order.

* Fix compiler warnings (division by zero).

When constructing floating-point infinity values, divide by floating-point zero
rather than integer zero, in order to avoid compiler warnings.

* Fix missing return statements/unreachable code.

- We also add a macro ASSERT_UNREACHABLE(), which is roughly equivalent to
  "assert(false)" but is also able to leverage the existing error-reporting
  and stack-trace machinery.

* Fix function return type (broadcast_queue.hpp).

* Fix signed/unsigned comparisons.

- In some cases involving ordering comparisons, it is important to ensure that
  the operands are within range of the signed type actually used to perform the
  comparison. For this purpose, this patch adds a family of functions called
  "truncate_check" to perform these range checks at runtime. (Of course, if we
  can ensure statically that a given range check is satisfied, then we may
  remove the invocation of truncate_check() and avoid the runtime overhead.)

* Fix unused variables (#460, #479).

* Fix strict-aliasing issues.

* Use boost::filesystem for temporary paths (#462).

- One of the C-API unit tests (capi_models.cxxtest) was attempting to write to a
  path of the form "/var/tmpFILE" instead of "/var/tmp/FILE", which was causing
  the test to fail due to permissions issues on Linux. This patch replaces the
  temporary path with an implementation based on boost::filesystem.

- We also switch to an auto-generated temporary path rather than a hard-coded
  path in the capi_sframe unit test, in order to avoid errors if the current
  user does not have permission to write the path in question.

- Finally, we replace a use of the deprecated function tmpnam(), addressing a
  compiler warning (#462).

* Implement several new features in run_cpp_tests.py.

- Make caching behavior optional, so that we can avoid hashing many large files
  when this is not necessary.

- Add an option to disable random shuffling of the individual tests (i.e., the
  "--schedule-random" flag in ctest). This makes it much easier to compare
  results across multiple runs.

- Add an option to disable expensive tests (i.e., those that typically take
  longer than a few seconds); this is useful to get a quick overall read on
  correctness.

- Display ctest output incrementally via subprocess.Popen, rather than saving it
  all until the end of the run.

* Address compiler warnings for protobuf includes.

- Some auto-generated protobuf source files cause compiler warnings (e.g.,
  -Wunused-function). Existing sources that include these files guard them with
  clang pragmas to disable the warnings, but GCC does not recognize the
  pragmas, causing additional compiler warnings. Instead, we tell CMake to add
  GCC-specific flags to disable the warnings in the command-line invocations
  for the relevant source files.

* Fix deprecation warning for Boost header (template_arity_spec.hpp).

* Prevent excessive debugging output from Boost build ("common.copy", "common.mkdir", etc.).

* Fix CMake script to restrict C++-specific compiler flag to C++ source files.

Builds of external source files were triggering compiler warnings due to the
presence of the "-fvisibility-inlines-hidden" flag, which is only valid for C++
source (not plain C). This patch restricts this flag to C++ source files only.

* Add missing cases in conditionals/switch-case blocks (#459, #483).

* Fix order of operations (xor vs. equals).

* Fix warnings regarding C++ comment syntax: avoid backslash and '/*' tokens (#467).

* Fix minor format-string issues (#470).

- snprintf() expects the format specifier "%lld" to refer to a value of type
  "long long", not flex_int; we assert statically that flex_int is synonymous
  with "long", and add a static cast.

- Use of the null terminator "\0" in the format string for sscanf() elicits a
  GCC compiler warning; we remove this character.

* Fix unused variable in test/random/test_alias.cpp.

The variable "k" is assigned to, but not subsequently used, in the
run_alias_benchmark() function. Rather than remove it, we use it as a dummy
accumulator, in order to preserve the existing sequence of random number
generation calls.

* Fix variable shadowing issue in sparse_similarity/item_processing.hpp.

The variable "row_idx", referring to an atomic counter shared between threads,
was incorrectly shadowed by another local variable of the same name. This patch
renames the outer-scope variable, and updates one of the corresponding
references in the inner scope.

* Fix return type (void functions incorrectly marked as returning bool).

* Fix potentially uninitialized values (#481).

* Factor out utility function "ceil_divide" (also fixes -Wunused-function warnings).

* Add missing braces in std::array initialization (#477).

Extra braces are required in C++11; see:
https://en.cppreference.com/w/cpp/container/array

* Add missing virtual method override annotations.

* Fix implicit conversion of constant (#465).

* Fix boolean value returned from main() (#466).

* Fix std::move invocations on temporary variables (#469).

- We still make std::move calls in the case of the gl_string unit test, to
  attempt to preserve the existing test semantics.

* Fix potential side-effects in typeid() call (#472).

* Fix abs() call to refer to intended operand instead of comparison result (#474).

- Previously the code was testing "abs(stats.residual < 1e-5)" instead of
  "abs(stats.residual) < 1e-5".

* Add local directives to disable warnings on overloaded virtual methods (-Woverloaded-virtual).

- In some cases, we have a base class method overridden by a derived class
  method of the same name, but different type signature. This causes clang to
  generate compiler warnings (-Woverloaded-virtual). Ideally, we would simply
  rename the methods in the derived class, but this may require other API
  changes. For now, we instead add preprocessor directives to prevent these
  warnings at a few key sites.

* Remove test of tc_ft_type_enum against NULL (#471).

- Previously we ran CHECK_NOT_NULL on a value of type tc_ft_type_enum. This is
  likely not intended, since this is not a pointer type, and in fact may have
  incorrectly resulted in errors thrown upon receiving the value FT_TYPE_INTEGER
  (= 0). This patch removes that check.

* Fix uninitialized value in TF-IDF computation.

* Disable -Wsign-compare warning for auto-generated Cython source files.

* Disable some warnings for selected external source files (as well as CoreML-related internal files).

* Fix uninitialized variable in unity_sframe.

* Add #ifdef guards around compiler pragma directives to prevent GCC warnings.

* Fix memory-clearing behavior in flexible_type.

- In order to clear a flexible_type value, in addition to setting val.intval
  (the first 8 bytes) and val.stored_type (the last 4 bytes), we must also set
  val.dtval.m_microsecond (the middle 4 bytes). Previously, these 4 bytes may
  have been uninitialized on some uses, causing GCC compiler warnings.

* Add missing argument in image similarity GPU test case.

* Explicitly specify Python version for virtualenv.

- This seems to be necessary in some environments when both Python 2.x and
  Python 3.x are installed on macOS.

* Add missing API_AVAILABLE annotations for macOS.

- This fixes several compiler warnings about specific APIs only being available
  from macOS 10.13 (or 10.14) onwards.

* Enable -Werror on Linux (and in release builds).

* Remove global -Werror exceptions.