Fix symbol collision in dmlc fileio
Fixes:
```
[ 90%] Linking CXX shared library libunity_shared.so
(symbol from plugin): warning: memset used with constant zero length
parameter; this
could be due to transposed parameters
/build/src/fileio/dmlcio/./io.h:71:0: error: type of
'_ZTVN4dmlc10SeekStreamE' does not match original declaration [-Werror]
 class SeekStream: public Stream {
 ^
/build/src/fileio/dmlcio/io.h:71:0: error: type of
'_ZTVN4dmlc10SeekStreamE' does not match original declaration [-Werror]
 class SeekStream: public Stream {
 ^
/build/src/external/xgboost/subtree/rabit/include/dmlc/io.h:86:0: note:
previously declared here
 class SeekStream: public Stream {
 ^
/build/src/fileio/dmlcio/./io.h:32:0: error: type of
'_ZTVN4dmlc6StreamE' does not match original declaration [-Werror]
 class Stream {
 ^
/build/src/fileio/dmlcio/io.h:32:0: error: type of '_ZTVN4dmlc6StreamE'
does not match original declaration [-Werror]
 class Stream {
 ^
/build/src/external/xgboost/subtree/rabit/include/dmlc/io.h:28:7: note:
previously declared here
 class Stream {  // NOLINT(*)
       ^
lto1: fatal error: errors during merging of translation units
lto1: all warnings being treated as errors
```