Fix visualization build on Xcode 12 Beta
The latest beta of Xcode 12 results in link errors for the visualization
client, due to an under-specified destination in how we build:
```
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in NSWindowWorkaround.o
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in CustomWebKitView.o
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in Error.o
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in ViewController.o
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in JSON.o
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in AppData.o
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization)
  "__swift_FORCE_LOAD_$_swiftCompatibility51", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_Turi_Create_Visualization in NSWindowWorkaround.o
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_Turi_Create_Visualization in CustomWebKitView.o
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_Turi_Create_Visualization in Error.o
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_Turi_Create_Visualization in ViewController.o
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_Turi_Create_Visualization in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_Turi_Create_Visualization in JSON.o
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_Turi_Create_Visualization in AppData.o
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility51_$_Turi_Create_Visualization)
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_Turi_Create_Visualization in NSWindowWorkaround.o
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_Turi_Create_Visualization in CustomWebKitView.o
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_Turi_Create_Visualization in Error.o
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_Turi_Create_Visualization in ViewController.o
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_Turi_Create_Visualization in AppDelegate.o
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_Turi_Create_Visualization in JSON.o
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_Turi_Create_Visualization in AppData.o
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_Turi_Create_Visualization)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The fix is to specify the scheme and destination on the command line
args to xcodebuild (for now, limited to x86_64).