Use std::abs instead of C abs function
This automatically handles int vs. float in llvm 8.0, avoiding this
warning:

```
/build/src/ml_data/column_statistics.cpp:569:177: error: using integer absolute value function 'abs' when argument is of floating point type [-Werror,-Wabsolute-value]
    do { const double _CHECK_OP_v1_ = statistics[i].mean; const double _CHECK_OP_v2_ = other->statistics[i].mean; const double _CHECK_OP_delta_ = 1e-6; if (__builtin_expect( !(abs((_CHECK_OP_v1_) - (_CHECK_OP_v2_)) <= _CHECK_OP_delta_), 0)) { auto throw_error = [&]() { std::ostringstream ss; ss << "Assertion failed: (" << "/build/src/ml_data/column_statistics.cpp" << ":" << 569 << "): " << "abs(" << "statistics[i].mean" << " - " << "other->statistics[i].mean" << ") <= " << "1e-6" << ". [" << "abs(" << _CHECK_OP_v2_ << " - " << _CHECK_OP_v1_ << ") > " << _CHECK_OP_delta_ << "]" << std::endl; if(6 >= global_logger().get_log_level()) (log_stream_dispatch<(6 >= 1)>::exec(6,"/build/src/ml_data/column_statistics.cpp", __func__ ,569) ) << ss.str(); __print_back_trace(); do { auto throw_error = [&]() __attribute__((cold, noinline, noreturn)) { write_annotated_stack_trace_if_configured(std::cerr); if(6 >= global_logger().get_log_level()) (log_stream_dispatch<(6 >= 1)>::exec(6,"/build/src/ml_data/column_statistics.cpp", __func__ ,569) ) << (ss.str()) << std::endl; throw(std::string(ss.str())); }; throw_error(); } while(0); }; throw_error(); __builtin_unreachable(); } } while (0);
                                                                                                                                                                                ^
/build/src/ml_data/column_statistics.cpp:569:177: note: use function 'std::abs' instead
    do { const double _CHECK_OP_v1_ = statistics[i].mean; const double _CHECK_OP_v2_ = other->statistics[i].mean; const double _CHECK_OP_delta_ = 1e-6; if (__builtin_expect( !(abs((_CHECK_OP_v1_) - (_CHECK_OP_v2_)) <= _CHECK_OP_delta_), 0)) { auto throw_error = [&]() { std::ostringstream ss; ss << "Assertion failed: (" << "/build/src/ml_data/column_statistics.cpp" << ":" << 569 << "): " << "abs(" << "statistics[i].mean" << " - " << "other->statistics[i].mean" << ") <= " << "1e-6" << ". [" << "abs(" << _CHECK_OP_v2_ << " - " << _CHECK_OP_v1_ << ") > " << _CHECK_OP_delta_ << "]" << std::endl; if(6 >= global_logger().get_log_level()) (log_stream_dispatch<(6 >= 1)>::exec(6,"/build/src/ml_data/column_statistics.cpp", __func__ ,569) ) << ss.str(); __print_back_trace(); do { auto throw_error = [&]() __attribute__((cold, noinline, noreturn)) { write_annotated_stack_trace_if_configured(std::cerr); if(6 >= global_logger().get_log_level()) (log_stream_dispatch<(6 >= 1)>::exec(6,"/build/src/ml_data/column_statistics.cpp", __func__ ,569) ) << (ss.str()) << std::endl; throw(std::string(ss.str())); }; throw_error(); } while(0); }; throw_error(); __builtin_unreachable(); } } while (0);
                                                                                                                                                                                ^~~
                                                                                                                                                                                std::abs
```