Gitignore cleanup (#408)
* Remove superfluous doc folder from gitignore

It causes lots of other random folders named `doc` to get
excluded (including tracked files in src).

* Remove `tags` from gitignore

It's ignoring lots of valid things

* Remove `.mo` from gitignore

There seem to be legit .mo files under deps that are being tracked.

* Remove *.log from .gitignore

There are legit tracked files in deps with extension .log.

* Remove a couple more superfluous ignores

* Remove some ignores from xgboost source drop

They are ignoring some of the files we have committed into the repo.

* Remove .txt from xgboost/subtree/rabit gitignore

We have tracked file
src/external/xgboost/subtree/rabit/doc/python-requirements.txt

* Remove xcuserdata files

These generally never should be tracked.

* Fix build break

Not sure if this was broken for anyone else, but I was getting:

```
In file included from /Users/zach/turicreate/src/unity/extensions/additional_sframe_utilities.cpp:15:
/Users/zach/turicreate/src/unity/extensions/additional_sframe_utilities.hpp:15:32: error: unknown type name 'image_type'; did you mean 'turi::image_type'?
void image_load_to_numpy(const image_type& img, size_t outptr_addr,
                               ^~~~~~~~~~
                               turi::image_type
/Users/zach/turicreate/src/image/image_type.hpp:34:7: note: 'turi::image_type' declared here
class image_type {
      ^
1 error generated.
```